app = "lexium-api-marcelo-20251003x"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false   # <- importante
  min_machines_running = 1

  [http_service.concurrency]
    soft_limit = 20
    hard_limit = 40
    type = "requests"

[[mounts]]
  source = "data_vol"
  destination = "/app/storage"

[checks]
  [checks.ping]
    port = 8080
    type = "http"
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/api/ping"
    grace_period = "10s"
