name: Fly Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly (force fast builder)
        run: |
          flyctl deploy \
            -a lexium-api-marcelo-20251003x \
            --remote-only \
            --build-only \
            --vm-size shared-cpu-1x \
            --ha=false \
            --config fly.toml \
            --dockerfile Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Launch final instance
        run: |
          flyctl deploy -a lexium-api-marcelo-20251003x --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Check status
        run: |
          flyctl status -a lexium-api-marcelo-20251003x
          flyctl logs -a lexium-api-marcelo-20251003x --since 5m
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
