name: "Fly - Set Secrets"

on:
  workflow_dispatch:

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@v1

      # Ver opcionalmente qué app vamos a tocar (debug seguro)
      - name: Show app name
        run: echo "App => $FLY_APP_NAME"

      # Envía tu OPENAI_API_KEY (user key sk-...)
      - name: Set OPENAI_API_KEY in Fly
        run: |
          flyctl secrets set OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" --app "$FLY_APP_NAME"

      # (Opcional pero recomendable) elimina OPENAI_PROJECT si existe,
      # ya que con user key sk-... no se usa
      - name: Unset OPENAI_PROJECT if present
        run: |
          flyctl secrets unset OPENAI_PROJECT --app "$FLY_APP_NAME" || true

      # (Opcional) lista los nombres de secrets para confirmar
      - name: List secrets (names only)
        run: |
          flyctl secrets list --app "$FLY_APP_NAME"
