name: Fly Start
on: workflow_dispatch

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Start all machines (if stopped)
        run: |
          flyctl machines list -a lexium-api-marcelo-20251003x --json | \
          node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const a=JSON.parse(s);for(const m of a){console.log('Starting',m.id);}})"
          # Si hay solo 1 máquina, intenta arrancarla (sin jq)
          MID=$(flyctl machines list -a lexium-api-marcelo-20251003x | awk 'NR==2{print $1}')
          if [ -n \"$MID\" ]; then flyctl machine start $MID -a lexium-api-marcelo-20251003x || true; fi
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
